name: Download Azure Cosmos DB Emulator and Show Checksum

on:
  workflow_dispatch:

jobs:
  download-and-show-checksum:
    runs-on: windows-latest

    env:
      COSMOSDB_URL: "https://aka.ms/cosmosdb-emulator"
      COSMOSDB_FILE: "cosmosdb-emulator.msi"

    steps:
      - name: Download Cosmos DB Emulator
        run: |
          Invoke-WebRequest -Uri $env:COSMOSDB_URL -OutFile $env:COSMOSDB_FILE

      - name: Compute and Display SHA256 Checksum
        run: |
          $hash = Get-FileHash -Path $env:COSMOSDB_FILE -Algorithm SHA256
          Write-Output "SHA256 checksum of downloaded file: $($hash.Hash)"
