name: Download WSI and Show Checksum

on:
  workflow_dispatch:

jobs:
  download-and-show-checksum:
    runs-on: windows-latest

    env:
      COSMOSDB_URL: "https://github.com/microsoft/WSL/releases/download/2.5.7/wsl.2.5.7.0.x64.msi"
      COSMOSDB_FILE: "wsi.msi"

    steps:
      - name: Download Cosmos DB Emulator
        run: |
          Invoke-WebRequest -Uri $env:COSMOSDB_URL -OutFile $env:COSMOSDB_FILE

      - name: Compute and Display SHA256 Checksum
        run: |
          $hash = Get-FileHash -Path $env:COSMOSDB_FILE -Algorithm SHA256
          Write-Output "SHA256 checksum of downloaded file: $($hash.Hash)"
