name: Python Issues Report 

on:
  # push:
  #   branches:
  #     - setup-actions

  workflow_dispatch:

jobs:
  generate-issue-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📦 Install dependencies
        run: |
          set -e
          python -m venv .venv
          source .venv/bin/activate
          pip install openpyxl requests 

      - name: Run issue report script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          source .venv/bin/activate
          python scripts/extract_issues_java.py
        
      - name: 📤 Upload generated Excel file
        uses: actions/upload-artifact@v4
        with:
          name: java-issues-label-flags
          path: issues_setup_java.xlsx